**RESULT FOR THE DATA ANALYSIS**

--PAID APPS HAVE BETTER RATINGS
--APPS SUPPORTING BETWEEN 10 AND 30 LANGUAGES HAVE BETTER RATING
--FINANCE AND BOOK APPS HAVE LOW RATINGS
--APPS WITH THE LONGER DESCRIPTION HAVE BETTER RATINGS
--A NEW APP SHOULD AIM FOR AN AVERAGE RATING ABOVE 3.5 
--GAMES AND ENTERTAINMENT HAVE HIGH COMPETITION